# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.


report: "report/workflow.rst"

# Allow users to fix the underlying OS via singularity.
singularity: "docker://continuumio/miniconda3"

include: "rules/common.smk"

rule all:
    input:
        expand("results/concatenated/{sample}.{paired}.fq.gz", sample=samples['sample'], paired=['R1','R2'])

include: "rules/quality_control.smk"